### ISSUE TITLE
Tensorboard web UI

### ISSUE THREAD

**Issue by mlleo** [imirzadeh/Teacher-Assistant-Knowledge-Distillation#14]
Hi! First, thanks for your nice code and paper!
I have some trouble to see the tensorboard by web UI. When I started training, then they let me know the URL, but it does not work. Is there other way that I can see the tensorboard?? I mean... like graph during training etc...

**Comment by imirzadeh** [comment]
Hi,

I don't use Tensorboard for logging my experiments. I use another web service for this matter.
If you have a specific result in your mind, I can share with you the links to that service.

**Comment by mlleo** [comment]
Thanks for your reply! I'm just studying code related to "knowledge distillation", so i just want to know how can i check the accuracy of the network! That's why i want to know how to see the log!

**Comment by imirzadeh** [comment]
Oh, I see.  Since I use NNI for hyper-parameter search, each std output for a specific trial, will be saved to a file for that trial. you can read the file or you can change the prints to save to a file.
