### ISSUE TITLE
Training Issue (problem with nni)

### ISSUE THREAD

**Issue by userb2020** [imirzadeh/Teacher-Assistant-Knowledge-Distillation#2]
Hello, I read your paper and it was really interesting.
So I want to run you code, however, I got an error that occurs at 

torch.manual_seed(config['seed'])

and the error is

TypeError: 'NoneType' object is not subscriptable

I am new to nni api so I think this error is trivial.
But I do not know how to solve this problem.

Could you help me how to deal this problem?

**Comment by imirzadeh** [comment]
Hi,   
Thank you and sorry for the delay. I'm very busy these days.   
You need to run the code with nni:   
`nnictl create --config config.yml`

I think you are running the code alone by running `python train.py` command from the terminal. You need to put this command in config.yml file and run nnictl. Then, nnictl will run the code with this command.

**Comment by wanghenry812** [comment]
Hello, I have encountered the same problem.I am new to nni api too.May i ask you solve it now?

**Comment by imirzadeh** [comment]
Hi.

As explained earlier, you need to run the code by first editing config.yml and then running `nnictl create --config config.yml    `
more details are in the [documentation](https://github.com/imirzadeh/Teacher-Assistant-Knowledge-Distillation/blob/master/readme.pdf)
